## Data Cleaning Tasks

* Missing Values
** Function to extract salary from benefits
** Extract info from benefits
** Extract info from description
* Feature Selection
* Encoding
* Text Cleaning(extract key information)
* * Try neural network

In [1]:
import pandas as pd

data = pd.read_csv('fake_job_postings.csv')
data.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

Encoding/
Text cleaning/
Feature selection/
Missing values

## Feature Selection(Manual)

In [2]:
data.isna().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2695
benefits                7210
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

#### Drop columns not needed

In [46]:
df = data.drop('job_id', axis=1)
df = df.drop('salary_range', axis=1)
df.tail()

,title,location,department,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
17875,Account Director - Distribution,"CA, ON, Toronto",Sales,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,Payroll Accountant,"US, PA, Philadelphia",Accounting,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17878,Graphic Designer,"NG, LA, Lagos",NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,Web Application Developers,"NZ, N, Wellington",Engineering,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

## Missing values

In [47]:
data.isna().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2695
benefits                7210
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [48]:
df['department'] = df['department'].fillna('Other')
df['location'] = df['location'].fillna('Unknown')
df['company_profile'] = df['company_profile'].fillna('No Company Profile')
df['description'] = df['description'].fillna('No Description')
df['requirements'] = df['requirements'].fillna('Unknown Requirements')
df['benefits'] = df['benefits'].fillna('No Listed Benefits')
df['employment_type'] = df['employment_type'].fillna('Unknown')
df['required_experience'] = df['required_experience'].fillna('Unknown')
df['required_education'] = df['required_education'].fillna('Unknown')
df['industry'] = df['industry'].fillna('Unknown')
df['function'] = df['function'].fillna('Unknown')

In [49]:
df.isna().sum()

title                  0
location               0
department             0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
dtype: int64

In [50]:
df['department'].value_counts()

Other                         11548
Sales                           551
Engineering                     487
Marketing                       401
Operations                      270
                              ...
Customer Service Rep.             1
I9 Manufacturing (345)            1
Organisational Development        1
DSD                               1
Hospitality                       1
Name: department, Length: 1337, dtype: int64

In [8]:
df.head(3)
df['benefits'][1]

'What you will get from usThrough being part of the 90 Seconds team you will gain:experience working on projects located around the world with an international brandexperience working with a variety of clients and on a large range of projectsopportunity to drive and grow production function and teama positive working environment with a great teamPay$40,000-$55,000Applying for this role with a VIDEOBeing a video business, we understand that one of the quickest ways that we can assess your suitability for this role, and one of the quickest ways that you can apply for it, is for you to submit a 60-90 second long video telling us about yourself, your experience and why you think you would be perfect for the role. \xa0It’s not about being a filmmaker or making a really creative video. \xa0A simple video filmed with a smart phone or web cam will be fine. Please also include where you are based and when you can start.You can upload the video onto YouTube or Vimeo (or similar) as a Draft or Live link.APPLICATIONS DUE by 5pm on Wednesday 18th July 2014 -\xa0Once you have a video ready, apply for this role via the following link together with a cover letter and your CV.\xa0After we have watched your video and get an idea of your suitability for the role, we will email the shortlisted candidates'

# MODEL

In [43]:
data.head(1)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0

In [51]:
#Cleaning text in description series

import regex as re

df['description'] = df['description'].str.lower()
df['description'] = df['description'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df.head()

,title,location,department,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,Marketing Intern,"US, NY, New York",Marketing,"We're Food52, and we've created a groundbreaki...",food52 a fastgrowing james beard awardwinning ...,Experience with content management systems a m...,No Listed Benefits,0,1,0,Other,Internship,Unknown,Unknown,Marketing,0
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,"90 Seconds, the worlds Cloud Video Production ...",organised focused vibrant awesomedo you hav...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,Unknown,Marketing and Advertising,Customer Service,0
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",Other,Valor Services provides Workforce Solutions th...,our client located in houston is actively seek...,Implement pre-commissioning and commissioning ...,No Listed Benefits,0,1,0,Unknown,Unknown,Unknown,Unknown,Unknown,0
3,Account Executive - Washington DC,"US, DC, Washington",Sales,Our passion for improving quality of life thro...,the company esri environmental systems resear...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,Bill Review Manager,"US, FL, Fort Worth",Other,SpotSource Solutions LLC is a Global Human Cap...,job title itemization review managerlocation f...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [52]:
#Tokenizing description series
import nltk 
from nltk.tokenize import word_tokenize

df['description_token'] = df['description'].apply(word_tokenize)
df.head(1)

,title,location,department,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,description_token
0,Marketing Intern,"US, NY, New York",Marketing,"We're Food52, and we've created a groundbreaki...",food52 a fastgrowing james beard awardwinning ...,Experience with content management systems a m...,No Listed Benefits,0,1,0,Other,Internship,Unknown,Unknown,Marketing,0,"[food52, a, fastgrowing, james, beard, awardwi..."

In [53]:
#remove stopwords from description
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
df['description_clean'] =  df['description_token'].apply(lambda x: [word for word in x if word not in stop_words])
df.head(1)

,title,location,department,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,description_token,description_clean
0,Marketing Intern,"US, NY, New York",Marketing,"We're Food52, and we've created a groundbreaki...",food52 a fastgrowing james beard awardwinning ...,Experience with content management systems a m...,No Listed Benefits,0,1,0,Other,Internship,Unknown,Unknown,Marketing,0,"[food52, a, fastgrowing, james, beard, awardwi...","[food52, fastgrowing, james, beard, awardwinni..."

In [55]:
#join string back for analysis

def combine_words(words_list):
    # Combine the words into a single string with spaces
    combined_string = " ".join(words_list)
    
    return combined_string


df["Total"] = df["description_clean"].apply(combine_words)

# Print the DataFrame
df.head()

,title,location,department,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,description_token,description_clean,Total
0,Marketing Intern,"US, NY, New York",Marketing,"We're Food52, and we've created a groundbreaki...",food52 a fastgrowing james beard awardwinning ...,Experience with content management systems a m...,No Listed Benefits,0,1,0,Other,Internship,Unknown,Unknown,Marketing,0,"[food52, a, fastgrowing, james, beard, awardwi...","[food52, fastgrowing, james, beard, awardwinni...",food52 fastgrowing james beard awardwinning on...
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,"90 Seconds, the worlds Cloud Video Production ...",organised focused vibrant awesomedo you hav...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,Unknown,Marketing and Advertising,Customer Service,0,"[organised, focused, vibrant, awesomedo, you, ...","[organised, focused, vibrant, awesomedo, passi...",organised focused vibrant awesomedo passion cu...
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",Other,Valor Services provides Workforce Solutions th...,our client located in houston is actively seek...,Implement pre-commissioning and commissioning ...,No Listed Benefits,0,1,0,Unknown,Unknown,Unknown,Unknown,Unknown,0,"[our, client, located, in, houston, is, active...","[client, located, houston, actively, seeking, ...",client located houston actively seeking experi...
3,Account Executive - Washington DC,"US, DC, Washington",Sales,Our passion for improving quality of life thro...,the company esri environmental systems resear...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,"[the, company, esri, environmental, systems, r...","[company, esri, environmental, systems, resear...",company esri environmental systems research in...
4,Bill Review Manager,"US, FL, Fort Worth",Other,SpotSource Solutions LLC is a Global Human Cap...,job title itemization review managerlocation f...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,"[job, title, itemization, review, managerlocat...","[job, title, itemization, review, managerlocat...",job title itemization review managerlocation f...

In [13]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

transformer = TfidfTransformer(smooth_idf = False)
count_vectorizer = CountVectorizer(ngram_range = (1,2))

In [57]:
train_counts = count_vectorizer.fit_transform(df['Total'].values)

train_tfidf = transformer.fit_transform(train_counts)
train_counts

<17880x777343 sparse matrix of type '<class 'numpy.int64'>'
	with 3388569 stored elements in Compressed Sparse Row format>

In [61]:
X = train_tfidf
y = df['fraudulent']

In [65]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 3)

In [68]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

Adab = AdaBoostClassifier(DecisionTreeClassifier(max_depth = 3), n_estimators = 5)
Adab.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3),
                   n_estimators=5)

In [69]:
Adab.score(X_train, y_train)

0.9649049217002237

In [70]:
Adab.score(X_test, y_test)

0.9661633109619687

## DATA IMBALANCE

In [ ]:
print('The number of Non-Frauds are: ' + str(data['fraudulent'].value_counts()[0]) + ' which is ', round(data['fraudulent'].value_counts()[0]/len(data) * 100,2), '% of the dataset')
print('The number of Frauds are: ' + str(data['fraudulent'].value_counts()[1]) + ' which is ', round(data['fraudulent'].value_counts()[1]/len(data) * 100,2), '% of the dataset')

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
# Shuffle the Dataset.
shuffled_df = data.sample(frac=1,random_state=4)

# Put all the fraud class in a separate dataset.
fraud_df = data.loc[shuffled_df['fraudulent'] == 1]

#Randomly select 492 observations from the non-fraud (majority class)
non_fraud_df = shuffled_df.loc[shuffled_df['fraudulent'] == 0].sample(n=492,random_state=42)

# Concatenate both dataframes again
normalized_df = pd.concat([fraud_df, non_fraud_df])

#plot the dataset after the undersampling
plt.figure(figsize=(8, 8))
sns.countplot('fraudulent', data=normalized_df)
plt.title('Balanced Classes')
plt.show()