In [1]:
# Loading neccesary libraries:

import random
import numpy as np
import pandas as pd

In [3]:
# To print multiple outputs
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
# Set it to None to display all columns in the dataframe
pd.set_option('display.max_columns', None)

# Import dataset

In [3]:

from google.colab import drive
drive.mount('/content/gdrive')

ModuleNotFoundError: No module named 'google.colab'

In [9]:
#Reading the data from google drive
# data=pd.read_csv('/content/gdrive/MyDrive/Dataset_CapstoneProject/newFile.csv')
df = pd.read_csv('./newFile.csv')
#Print that data imported successfully
print("Data imported successfully")

Data imported successfully

# View top 10 rows of dataset

In [10]:
#Write your code here
df.head(10)

,title,salary_range,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,Country,State,City,has_company_profile
0,Marketing Intern,NaN,"Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,US,NY,New York,1
1,Customer Service - Cloud Video Production,NaN,Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,NZ,,Auckland,1
2,Commissioning Machinery Assistant (CMA),NaN,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,Other,0,US,IA,Wever,1
3,Account Executive - Washington DC,NaN,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,US,DC,Washington,1
4,Bill Review Manager,NaN,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,US,FL,Fort Worth,1
5,Accounting Clerk,NaN,Job OverviewApex is an environmental consultin...,NaN,NaN,0,0,0,NaN,NaN,NaN,NaN,Accounting/Auditing,0,US,MD,,0
6,Head of Content (m/f),20000-28000,Your Responsibilities: Manage the English-spea...,Your Know-How: ...,Your Benefits: Being part of a fast-growing co...,0,1,1,Full-time,Mid-Senior level,Master's Degree,Online Media,Management,0,DE,BE,Berlin,1
7,Lead Guest Service Specialist,NaN,Who is Airenvy?Hey there! We are seasoned entr...,"Experience with CRM software, live chat, and p...",Competitive Pay. You'll be able to eat steak e...,0,1,1,NaN,NaN,NaN,NaN,Customer Service,0,US,CA,San Francisco,1
8,HP BSM SME,NaN,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,NaN,0,1,1,Full-time,Associate,NaN,Information Technology and Services,Other,0,US,FL,Pensacola,1
9,Customer Service Associate - Part Time,NaN,The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,1,0,Part-time,Entry level,High School or equivalent,Financial Services,Customer Service,0,US,AZ,Phoenix,1

In [11]:
df.describe()

,telecommuting,has_company_logo,has_questions,fraudulent,has_company_profile
count,17880.000000,17880.000000,17880.000000,17880.000000,17880.000000
mean,0.042897,0.795302,0.491723,0.048434,0.814989
std,0.202631,0.403492,0.499945,0.214688,0.388317
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,1.000000
50%,0.000000,1.000000,0.000000,0.000000,1.000000
75%,0.000000,1.000000,1.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
df.isnull ().sum ()

title                      0
salary_range           15012
description                1
requirements            2695
benefits                7210
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                   0
fraudulent                 0
Country                  346
State                    440
City                     440
has_company_profile        0
dtype: int64

In [13]:
df['description'] = df['description'].fillna('No Description')
df['requirements'] = df['requirements'].fillna('Unknown')
df['benefits'] = df['benefits'].fillna('Unknown')
df['employment_type'] = df['employment_type'].fillna('Unknown')
df['required_experience'] = df['required_experience'].fillna('Unknown')
df['required_education'] = df['required_education'].fillna('Unknown')
df['industry'] = df['industry'].fillna('Unknown')
df['Country'] = df['Country'].fillna('Unknown')
df['State'] = df['State'].fillna('Unknown')
df['City'] = df['City'].fillna('Unknown')

In [14]:
df.isna().sum()

title                      0
salary_range           15012
description                0
requirements               0
benefits                   0
telecommuting              0
has_company_logo           0
has_questions              0
employment_type            0
required_experience        0
required_education         0
industry                   0
function                   0
fraudulent                 0
Country                    0
State                      0
City                       0
has_company_profile        0
dtype: int64

In [8]:
df = data.drop('salary_range', axis=1)
df.tail()

,title,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,Country,State,City,has_company_profile
17875,Account Director - Distribution,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,CA,ON,Toronto,1
17876,Payroll Accountant,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,US,PA,Philadelphia,1
17877,Project Cost Control Staff Engineer - Cost Con...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,engineer,0,US,TX,Houston,1
17878,Graphic Designer,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0,NG,LA,Lagos,0
17879,Web Application Developers,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,NZ,N,Wellington,1

In [10]:
df.isna().sum()

title                  0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
Country                0
State                  0
City                   0
has_company_profile    0
dtype: int64

In [11]:
import regex as re
import regex as re

df['title'] = df['title'].str.lower()
df['title'] = df['title'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df['description'] = df['description'].str.lower()
df['description'] = df['description'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df['requirements'] = df['requirements'].str.lower()
df['requirements'] = df['requirements'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df['benefits'] = df['benefits'].str.lower()
df['benefits'] = df['benefits'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df['employment_type'] = df['employment_type'].str.lower()
df['employment_type'] = df['employment_type'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df['required_experience'] = df['required_experience'].str.lower()
df['required_experience'] = df['required_experience'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df['required_education'] = df['required_education'].str.lower()
df['required_education'] = df['required_education'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

df['industry'] = df['industry'].str.lower()
df['industry'] = df['industry'].apply(lambda x: re.sub(r'[^\w\d\s\']+', '', x))

In [12]:

#Tokenizing description series
import nltk 
from nltk.tokenize import word_tokenize
nltk.download('punkt')

df['title_token'] = df['title'].apply(word_tokenize)

df['description_token'] = df['description'].apply(word_tokenize)

df['requirements_token'] = df['requirements'].apply(word_tokenize)

df['benefits_token'] = df['benefits'].apply(word_tokenize)

df['employment_type_token'] = df['employment_type'].apply(word_tokenize)

df['required_experience_token'] = df['required_experience'].apply(word_tokenize)

df['required_education_token'] = df['required_education'].apply(word_tokenize)

df['industry_token'] = df['industry'].str.lower()

df.head(2)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\maste\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

,title,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,Country,State,City,has_company_profile,title_token,description_token,requirements_token,benefits_token,employment_type_token,required_experience_token,required_education_token,industry_token
0,marketing intern,food52 a fastgrowing james beard awardwinning ...,experience with content management systems a m...,no listed benefits,0,1,0,other,internship,unknown,unknown,Marketing,0,US,NY,New York,1,"[marketing, intern]","[food52, a, fastgrowing, james, beard, awardwi...","[experience, with, content, management, system...","[no, listed, benefits]",[other],[internship],[unknown],unknown
1,customer service cloud video production,organised focused vibrant awesomedo you hav...,what we expect from youyour key responsibility...,what you will get from usthrough being part of...,0,1,0,fulltime,not applicable,unknown,marketing and advertising,Customer Service,0,NZ,,Auckland,1,"[customer, service, cloud, video, production]","[organised, focused, vibrant, awesomedo, you, ...","[what, we, expect, from, youyour, key, respons...","[what, you, will, get, from, usthrough, being,...",[fulltime],"[not, applicable]",[unknown],marketing and advertising

In [13]:

#remove stopwords from description
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

df['title_clean'] = df['title_token'].apply(lambda x: [word for word in x if word not in stop_words])

df['description_clean'] = df['description_token'].apply(lambda x: [word for word in x if word not in stop_words])

df['requirements_clean'] = df['requirements_token'].apply(lambda x: [word for word in x if word not in stop_words])

df['benefits_clean'] = df['benefits_token'].apply(lambda x: [word for word in x if word not in stop_words])

df['employment_type_clean'] = df['employment_type_token'].apply(lambda x: [word for word in x if word not in stop_words])

df['required_experience_clean'] = df['required_experience_token'].apply(lambda x: [word for word in x if word not in stop_words])

df['required_education_clean'] = df['required_education_token'].apply(lambda x: [word for word in x if word not in stop_words])

df['industry_clean'] = df['industry_token'].apply(lambda x: [word for word in x if word not in stop_words])

df.head(2)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\maste\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

,title,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,Country,State,City,has_company_profile,title_token,description_token,requirements_token,benefits_token,employment_type_token,required_experience_token,required_education_token,industry_token,title_clean,description_clean,requirements_clean,benefits_clean,employment_type_clean,required_experience_clean,required_education_clean,industry_clean
0,marketing intern,food52 a fastgrowing james beard awardwinning ...,experience with content management systems a m...,no listed benefits,0,1,0,other,internship,unknown,unknown,Marketing,0,US,NY,New York,1,"[marketing, intern]","[food52, a, fastgrowing, james, beard, awardwi...","[experience, with, content, management, system...","[no, listed, benefits]",[other],[internship],[unknown],unknown,"[marketing, intern]","[food52, fastgrowing, james, beard, awardwinni...","[experience, content, management, systems, maj...","[listed, benefits]",[],[internship],[unknown],"[u, n, k, n, w, n]"
1,customer service cloud video production,organised focused vibrant awesomedo you hav...,what we expect from youyour key responsibility...,what you will get from usthrough being part of...,0,1,0,fulltime,not applicable,unknown,marketing and advertising,Customer Service,0,NZ,,Auckland,1,"[customer, service, cloud, video, production]","[organised, focused, vibrant, awesomedo, you, ...","[what, we, expect, from, youyour, key, respons...","[what, you, will, get, from, usthrough, being,...",[fulltime],"[not, applicable]",[unknown],marketing and advertising,"[customer, service, cloud, video, production]","[organised, focused, vibrant, awesomedo, passi...","[expect, youyour, key, responsibility, communi...","[get, usthrough, part, 90, seconds, team, gain...",[fulltime],[applicable],[unknown],"[r, k, e, n, g, , n, , v, e, r, n, g]"

In [39]:

#join string back for analysis

def combine_words(words_list):
    # Combine the words into a single string with spaces
    combined_string = " ".join(words_list)
    
    return combined_string


df["Total"] = df["description_clean"].apply(combine_words)

df['title_clean'] = df['title_clean'].apply(combine_words)

# df['description_clean'] = df['description_clean'].apply(combine_words)

df['requirements_clean'] = df['requirements_clean'].apply(combine_words)

df['benefits_clean'] = df['benefits_clean'].apply(combine_words)

df['employment_type_clean'] = df['employment_type_clean'].apply(combine_words)

df['required_experience_clean'] = df['required_experience_clean'].apply(combine_words)

df['required_education_clean'] = df['required_education_clean'].apply(combine_words)

df['industry_clean'] = df['industry_clean'].apply(combine_words)


# Print the DataFrame
df.head()

,title,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,Country,State,City,has_company_profile,title_token,description_token,requirements_token,benefits_token,employment_type_token,required_experience_token,required_education_token,industry_token,title_clean,description_clean,requirements_clean,benefits_clean,employment_type_clean,required_experience_clean,required_education_clean,industry_clean,Total
0,marketing intern,food52 a fastgrowing james beard awardwinning ...,experience with content management systems a m...,no listed benefits,0,1,0,other,internship,unknown,unknown,Marketing,0,US,NY,New York,1,"[marketing, intern]","[food52, a, fastgrowing, james, beard, awardwi...","[experience, with, content, management, system...","[no, listed, benefits]",[other],[internship],[unknown],unknown,marketing intern,"[food52, fastgrowing, james, beard, awardwinni...",experience content management systems major pl...,listed benefits,,internship,unknown,u n k n w n,food52 fastgrowing james beard awardwinning on...
1,customer service cloud video production,organised focused vibrant awesomedo you hav...,what we expect from youyour key responsibility...,what you will get from usthrough being part of...,0,1,0,fulltime,not applicable,unknown,marketing and advertising,Customer Service,0,NZ,,Auckland,1,"[customer, service, cloud, video, production]","[organised, focused, vibrant, awesomedo, you, ...","[what, we, expect, from, youyour, key, respons...","[what, you, will, get, from, usthrough, being,...",[fulltime],"[not, applicable]",[unknown],marketing and advertising,customer service cloud video production,"[organised, focused, vibrant, awesomedo, passi...",expect youyour key responsibility communicate ...,get usthrough part 90 seconds team gainexperie...,fulltime,applicable,unknown,r k e n g n v e r n g,organised focused vibrant awesomedo passion cu...
2,commissioning machinery assistant cma,our client located in houston is actively seek...,implement precommissioning and commissioning p...,no listed benefits,0,1,0,unknown,unknown,unknown,unknown,Other,0,US,IA,Wever,1,"[commissioning, machinery, assistant, cma]","[our, client, located, in, houston, is, active...","[implement, precommissioning, and, commissioni...","[no, listed, benefits]",[unknown],[unknown],[unknown],unknown,commissioning machinery assistant cma,"[client, located, houston, actively, seeking, ...",implement precommissioning commissioning proce...,listed benefits,unknown,unknown,unknown,u n k n w n,client located houston actively seeking experi...
3,account executive washington dc,the company esri environmental systems resear...,education bachelors or masters in gis business...,our culture is anything but corporatewe have a...,0,1,0,fulltime,midsenior level,bachelor's degree,computer software,Sales,0,US,DC,Washington,1,"[account, executive, washington, dc]","[the, company, esri, environmental, systems, r...","[education, bachelors, or, masters, in, gis, b...","[our, culture, is, anything, but, corporatewe,...",[fulltime],"[midsenior, level]","[bachelor, 's, degree]",computer software,account executive washington dc,"[company, esri, environmental, systems, resear...",education bachelors masters gis business admin...,culture anything corporatewe collaborative cre...,fulltime,midsenior level,bachelor 's degree,c p u e r f w r e,company esri environmental systems research in...
4,bill review manager,job title itemization review managerlocation f...,qualificationsrn license in the state of texas...,full benefits offered,0,1,1,fulltime,midsenior level,bachelor's degree,hospital health care,Health Care Provider,0,US,FL,Fort Worth,1,"[bill, review, manager]","[job, title, itemization, review, managerlocat...","[qualificationsrn, license, in, the, state, of...","[full, benefits, offered]",[fulltime],"[midsenior, level]","[bachelor, 's, degree]",hospital health care,bill review manager,"[job, title, itemization, review, managerlocat...",qualificationsrn license state texasdiploma ba...,full benefits offered,fulltime,midsenior level,bachelor 's degree,h p l h e l h c r e,job title itemization review managerlocation f...

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [16]:

# df['description_cv'] = cv.fit_transform(df.description).toarray()

# df['title_cv'] = df['title']

# # df['description_cv'] = df['description']

df['requirements_cv'] = cv.fit_transform(df['requirements'])
# df['requirements_cv'] = df['requirements_cv'].toarray()

# df['benefits_cv'] = df['benefits']

# df['employment_type_cv'] = df['employment_type']

# df['required_experience_cv'] = df['required_experience']

# df['required_education_cv'] = df['required_education']

# df['industry_cv'] = df['industry']

In [17]:
df['requirements_cv']

0          (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
1          (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
2          (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
3          (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
4          (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
                               ...
17875      (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
17876      (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
17877      (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
17878      (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
17879      (0, 22840)\t1\n  (0, 69372)\t5\n  (0, 12832)...
Name: requirements_cv, Length: 17880, dtype: object

In [40]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

transformer = TfidfTransformer(smooth_idf = False)
count_vectorizer = CountVectorizer(ngram_range = (1,2))

In [42]:
train_counts = count_vectorizer.fit_transform(df['Total'].values)

# train_counts = count_vectorizer.fit_transform(df[['title_clean', 'description_clean', 'requirements_clean', 'benefits_clean', 'employment_type_clean', 'required_experience_clean', 'required_education_clean', 'industry_clean']].values)

df['train_tfidf'] = transformer.fit_transform(train_counts)
train_counts

TypeError: ignored

In [53]:
df.head(1)

,title,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,Country,State,City,has_company_profile,title_token,description_token,requirements_token,benefits_token,employment_type_token,required_experience_token,required_education_token,industry_token,title_clean,description_clean,requirements_clean,benefits_clean,employment_type_clean,required_experience_clean,required_education_clean,industry_clean,Total,title_cv,requirements_cv,benefits_cv,employment_type_cv,required_experience_cv,required_education_cv,industry_cv
0,marketing intern,food52 a fastgrowing james beard awardwinning ...,experience with content management systems a m...,no listed benefits,0,1,0,other,internship,unknown,unknown,Marketing,0,US,NY,New York,1,"[marketing, intern]","[food52, a, fastgrowing, james, beard, awardwi...","[experience, with, content, management, system...","[no, listed, benefits]",[other],[internship],[unknown],unknown,marketing intern,"[food52, fastgrowing, james, beard, awardwinni...",experience content management systems major pl...,listed benefits,,internship,unknown,u n k n w n,food52 fastgrowing james beard awardwinning on...,marketing intern,experience with content management systems a m...,no listed benefits,other,internship,unknown,unknown

In [18]:
X = df['requirements_cv']
y = df['fraudulent']



```
# SMOTE Way 1:
```

In [19]:
from collections import Counter
Counter(y)

Counter({0: 17014, 1: 866})

In [20]:

from imblearn.over_sampling import SMOTE
smo = SMOTE(random_state=42)
X_smo,y_smo = smo.fit_resample(X,y)

ValueError: setting an array element with a sequence.

In [22]:
Counter(y_smo)

Counter({0: 17014, 1: 17014})

In [23]:
y_smo.shape

(34028,)

In [24]:
X_smo.shape

(34028, 777343)

In [25]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_smo,y_smo, test_size = 0.2, random_state = 3)

In [26]:

from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

Adab = AdaBoostClassifier(DecisionTreeClassifier(max_depth = 3), n_estimators = 5)
Adab.fit(X_train, y_train)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3),
                   n_estimators=5)

In [27]:

print("score for training dataset:",Adab.score(X_train, y_train))
print("score for test dataset:",Adab.score(X_test, y_test))
print("predict:",Adab.predict(X_test))

score for training dataset: 0.8310924987142753
score for test dataset: 0.83191301792536
predict: [1 1 1 ... 1 1 0]

In [21]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE

# Generate a sample dataset with imbalanced classes
X, y = make_classification(n_samples=10000, n_features=20, weights=[0.9], random_state=42)

# Print the class distribution
print('Original class distribution:')
print(pd.Series(y).value_counts())

Original class distribution:
0    8969
1    1031
dtype: int64

In [22]:
# Apply SMOTE to balance the classes
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Print the class distribution after applying SMOTE
print('Class distribution after applying SMOTE:')
print(pd.Series(y_resampled).value_counts())

AttributeError: 'NoneType' object has no attribute 'split'

In [27]:
from imblearn.over_sampling import SMOTE

# Create some example data
X = [[1, 2], [3, 4], [1, 2], [3, 4], [5, 6], [7, 8]]
y = [1, 0, 0, 1, 1, 1]

# Apply SMOTE to balance the classes
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X, y)

# Print the class distribution after applying SMOTE
import collections
print(collections.Counter(y_resampled))

ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 6